
name: "JfrogTEST"

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - uses: jfrog/setup-jfrog-cli@v4
    - run: echo $JFURL/artifactory/ronbz-docker-local/
    - run: echo ${{ secrets.JFURL }}
    - run: curl -X PUT -uadmin:${{ secrets.JFTOKEN }} -T "voy.txt" ${{ secrets.JFURL }}/artifactory/ronbz-docker-local/voy.txt
