
name: "JfrogTEST"

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - uses: jfrog/setup-jfrog-cli@v4
      env:
        JF_URL: ${{ vars.JF_URL }}
        JF_ACCESS_TOKEN: ${{ secrets.JFTOKEN }}
    - run: echo ${{ vars.JF_URL }}
    - run: jf rt ping
    - run: curl -X PUT -uronbz:${{ secrets.JFTOKEN }} -T "voy.txt" ${{ vars.JF_URL }}/artifactory/ronbz1-docker-local/voy.txt
