
name: JfrogCLI

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - uses: jfrog/setup-jfrog-cli@v4
    - run: echo $JFURL/artifactory/ronbz-generic-local/
    - run: echo ${{ secrets.JFURL }}
