
name: "JfrogTEST"

on: push

jobs:
  build:
    permissions:
      actions: read
      contents: read
      security-events: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v4.4.1
      env:
        JF_URL: ${{ vars.JF_URL }}
        JF_ACCESS_TOKEN: ${{ secrets.JFTOKEN }}
        JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: echo ${{ vars.JF_URL }}
    - run: jf rt ping
    ##- run: curl -X PUT -uronbz:${{ secrets.JFTOKEN }} -T "voy.txt" ${{ vars.JF_URL }}/artifactory/ronbz1-docker-local/voy.txt
    - name: Docker
      run: |
        docker build -t testfile:1 .
        docker tag testfile:1 kimt.jfrog.io/ronbz1-docker-local/testfile:1
    - run: jf docker scan kimt.jfrog.io/ronbz1-docker-local/testfile:1
    - run: |
        docker login kimt.jfrog.io -u ${{ secrets.JFUSERNAME }} --password ${{ secrets.JFPASSWORD }}
        docker push kimt.jfrog.io/ronbz1-docker-local/testfile:1


              
