name: "JFrog CLI"


on: push


jobs:
 build:
   runs-on: ubuntu-latest
  
   steps:
   - name: Checkout
     uses: actions/checkout@v4
   - uses: jfrog/setup-jfrog-cli@v3
   - run: echo $JFURL/artifactory/ronbz-generic-local/
   - run: echo ${{ secrets.JFURL }}
   - run: curl -X PUT -uvoyagers2:${{ secrets.JFTOKEN }} -T "voy.txt" ${{ secrets.JFURL }}/artifactory/ronbz-generic-local/voy.txt
