name: "JFrog CLI"


on: push


jobs:
 build:
   runs-on: ubuntu-latest
  
   steps:
   - name: Checkout
     uses: actions/checkout@v4
   - uses: jfrog/setup-jfrog-cli@v3
     env:
       JF_URL: ${{ secrets.JFURL }}
       JFTOKEN: ${{ secrets.JFTOKEN }}
   - run: echo $JF_URL/artifactory/ronbz-generic-local/
   - run: curl -X PUT -uvoyagers2:$JFTOKEN -T "voy.txt" $JF_URL/artifactory/ronbz-generic-local/
